CREATE TABLE IF NOT EXISTS author(
    authorId SERIAL PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    bookList TEXT[] NOT NULL
);

CREATE TABLE IF NOT EXISTS book(

)