CREATE TABLE IF NOT EXISTS author(
    id SERIAL PRIMARY KEY NOT NULL,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    bookList CHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS book(
    id SERIAL PRIMARY KEY NOT NULL,
    title VARCHAR(50) NOT NULL,
    printYear VARCHAR(50) NOT NULL,
    authorBook VARCHAR(50) NOT NULL
);